import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import AntDesignProvider from '@infrastructure/providers/AntDesignProvider';
import QueryProvider from '@infrastructure/providers/QueryProvider';

import DashboardLayout from '@components/layouts/DashboardLayout';

import '@styles/global.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <QueryProvider>
          <AntDesignProvider>
            <DashboardLayout>{children}</DashboardLayout>
          </AntDesignProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
